sudo: false
language: python

cache:
  - pip
  - directories:
    - .benchmarks
branches:
  only:
    - master

before_install:
  - pip install --upgrade pip setuptools wheel

matrix:
  include:
  - os: linux
    env: NAME=mypy
    python: "3.5.2"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep mypy | xargs pip install
    script: check/mypy

  - os: linux
    env: NAME=pylint
    python: "3.5.2"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep "pylint\|astroid" | grep -v "#" | xargs pip install
    script: check/pylint

  - os: linux
    env: NAME=format
    python: "3.5.2"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep yapf | xargs pip install
    script: check/format-incremental

  - os: windows
    env: NAME=pytest (Windows)
    language: sh
    python: "3.7.3"
    cache:
      - directories:
          - C:/Users/travis/Pip/Cache
    before_install:
      - choco install travis_windows_python
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    install:
      - python -m pip install --upgrade pip wheel
    script:
      - dir




