sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    python: "3.5"
    before_install:
      - pip install --upgrade pip setuptools wheel
    install:
      - pip install -r dev-requirements.txt
    script: continuous-integration/travis.sh "normal"
  - os: linux
    python: "2.7"
    before_install:
      - pip install --upgrade pip setuptools wheel
    install:
      - pip install -r python2.7-dev-requirements.txt
    script: continuous-integration/travis.sh "convert-and-test"
