sudo: false
language: python
env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - secure: "JYKp7BuS6wp9xRDm2qJLyWaBokaBeO6wCUMfCVqs04dXxc+gHTmSjIdUgi5uarhGrjxCiDxmWKk17nzbcY7MwigEYvHSqUdQtcxg00R3FmWWG7qMLAt6wCNodtWUYiZlq0qFFleh04F9ygLQl3Qbpya7pSpEO92BX7Nnjyfu0/aWuGwCd3Bizvaar5AzxsM2GAvC47SQM86F8osNiit2fRE9AW9wgtpQ89E2RvNP22eMbp79Ii0dFOEMOoxHyIABVqyL9RhnwT/CNrky6xeaMFGx9PKf6zEWBXIUeqUbLQZwB9llWyZKjKfwuQ7p9eYd4ou3jqNgnze9CCYXrj/nCydqduPICxDAMwD2TcDRENKUIdDUw+b1LVg79AHwGJAT8jFR8l/PPKoYbzjMCcGDcJrhKDLQS3K6nJAV1KIc9HpbQGMDr7LxVRvZNSxkwiR+r8hNJJ9r270zo3wfHaK6K86W47eSo7U1kwEDhx8WDLkuTUH1fss3QFnrZku6y01/hCpK7FPuKuTpE2IBgtF5B9XF7d8JdUPaHVM6yJPCY7zYBp411LiN22EcFxrSkDRZix22OmzATnNGKiUadXfLzNCFkxo420kofCm1kOI6dI6c4ZuvpjDwTuNa3LNt8uX4Ym6Zff83DThE0G8Q5hOeO31dUEw98hjN0Nk+D4KW2tU="
cache:
  directories:
  - ".benchmarks"
branches:
  only:
  - master
stages:
- test
- name: deploy
  if: type = push AND branch = master
matrix:
  include:
  - stage: test
    os: linux
    env:
    - NAME=mypy
    - secure: "JYKp7BuS6wp9xRDm2qJLyWaBokaBeO6wCUMfCVqs04dXxc+gHTmSjIdUgi5uarhGrjxCiDxmWKk17nzbcY7MwigEYvHSqUdQtcxg00R3FmWWG7qMLAt6wCNodtWUYiZlq0qFFleh04F9ygLQl3Qbpya7pSpEO92BX7Nnjyfu0/aWuGwCd3Bizvaar5AzxsM2GAvC47SQM86F8osNiit2fRE9AW9wgtpQ89E2RvNP22eMbp79Ii0dFOEMOoxHyIABVqyL9RhnwT/CNrky6xeaMFGx9PKf6zEWBXIUeqUbLQZwB9llWyZKjKfwuQ7p9eYd4ou3jqNgnze9CCYXrj/nCydqduPICxDAMwD2TcDRENKUIdDUw+b1LVg79AHwGJAT8jFR8l/PPKoYbzjMCcGDcJrhKDLQS3K6nJAV1KIc9HpbQGMDr7LxVRvZNSxkwiR+r8hNJJ9r270zo3wfHaK6K86W47eSo7U1kwEDhx8WDLkuTUH1fss3QFnrZku6y01/hCpK7FPuKuTpE2IBgtF5B9XF7d8JdUPaHVM6yJPCY7zYBp411LiN22EcFxrSkDRZix22OmzATnNGKiUadXfLzNCFkxo420kofCm1kOI6dI6c4ZuvpjDwTuNa3LNt8uX4Ym6Zff83DThE0G8Q5hOeO31dUEw98hjN0Nk+D4KW2tU="
    python: '3.6'
    install:
    - env |sed 's/./& /g'
    script: echo DONE
