sudo: false
language: python
matrix:
  include:
  - os: linux
    python: "3.5"
    env: MODE="normal" REQS="dev-requirements.txt"
  - os: linux
    python: "2.7"
    env: MODE="convert-and-test" REQS="python2.7-dev-requirements.txt"

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y protobuf-compiler libprotoc10
  - pip install --upgrade pip setuptools wheel

install:
  - pip install -r ${REQS}

script: continuous-integration/travis.sh "${MODE}"
