language: python
cache:
  directories:
  - ".benchmarks"
branches:
  only:
  - master
matrix:
  include:
  - stage: test
    os: windows
    env: NAME=pytest (Windows)
    language: sh
    python: '3.7.3'
    before_install:
      - # TODO(craiggidney): re-enable after https://github.com/quantumlib/Cirq/issues/2283 is resolved
      - powershell -command 'Set-MpPreference -DisableArchiveScanning $true'
      - powershell -command 'Set-MpPreference -DisableBehaviorMonitoring $true'
      - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
      - choco install python --version 3.7.3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel
    install:
      - python -m pip install -r requirements.txt
      - python -m pip install -r cirq/contrib/contrib-requirements.txt
      - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest --benchmark-skip

