apiVersion: v1
kind: Service
metadata:
  name: cirq-automerge-headless-svc
  labels:
    app: cirq-automerge
spec:
  clusterIP: None
  selector:
    app: cirq-automerge
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cirq-automerge
spec:
  selector:
    matchLabels:
      app: cirq-automerge # has to match .spec.template.metadata.labels
  serviceName: "automerge-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: cirq-automerge
    spec:
      containers:
      - name: cirq-automerge
        image: us-docker.pkg.dev/cirq-infra/cirq/automerge