name: Continuous Integration

on: [pull_request]

jobs:

  notebooks-branch:
    name: Notebook Tests (branch)
    runs-on: ubuntu-16.04
    steps:
      - name: nbmake
        uses: treebeardtech/nbmake-action@v0.2.1