name: Continuous Integration

on:
  schedule:
    # Checks out master by default.
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  macos:
    name: Pytest MacOS
    strategy:
      matrix:
        python-version: ['3.7']
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt', 'dev_tools/requirements/**/*.txt') }}
      - name: Pytest check
        run: python -c 'import bz2'
