name: Release cirq-unstable to PyPi

on:
  push:
    branches:
      - master
jobs:
  push_to_pypi:
    name: Push to PyPi
    runs-on: ubuntu-16.04
    env:
      NAME: dev-release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Generate new version
        run: ::set-env CIRQ_UNSTABLE_VERSION=$(dev_tools/packaging/generate-dev-version-id.sh)
      - run: echo "Deploying dev version '$CIRQ_UNSTABLE_VERSION'"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        if: ${{contains(env.CIRQ_UNSTABLE_VERSION, 'dev')}}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          python setup.py bdist_wheel
          twine upload dist/*